<a href="https://colab.research.google.com/github/MaxKuzmenko/linear-algebra/blob/main/Linear%20algebra.%20Vector.%20HomeWork.%20KuzMax13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Линейная алгебра для нейросетей. Векторы.

## Подготовка:

In [1]:
import numpy as np
from numpy.linalg import norm

In [2]:
# Списки сущностей:
names = {
    0: "Элерон'Таз",
    1: "Чилит-в-Глубинах",
    2: "Ротгарн Стопа",
    3: "Ульфгард Золотая Струя",
    4: "Мурка",
    5: "Красная машина",
    6: "Носит-под-Гузник",
    7: "Куремар",
}

vec_list = np.array([
    [3, 9, 3, 0, 8, 2, 0, 4, 2],        # Элерон'Таз
    [2, 7, 4, 9, 8, 3, 0, 5, 4],        # Чилит-в-Глубинах
    [9, 3, 2, 0, 1, 8, 0, 5, 9],        # Ротгарн Стопа
    [7, 2, 3, 7, 4, 6, 0, 2, 6],        # Ульфгард Золотая Струя
    [5, 8, 1, 7, 2, 9, 0, 2, 3],        # Мурка
    [25, 10, 10, 0, 20, 30, 0, 0, 15],  # Красная машина
    [3, 3, 3, 3, 3, 3, 3, 3, 3],        # Носит-под-Гузник
    [1, 3, 9, 5, 1, 1, 0, 9, 1],        # Куремар
])

mods = [
    2.0,  # Зелье божественной силы
    1.2,  # Зелье могущества
    0.5,  # Сонливость
]

potions = np.array([
    [3, 0, 0, 0, 0, 0, 0, 0, 0],      # Зелье силы
    [2, 1, 0, 0, 0, 1, 0, 1, 1],      # Зелье война
    [-2, -1, 0, 0, 0, 0, 4, 0, -1],   # Яд паралича
    [0, 0, 3, 0, 0, 0, 0, 0, -1],     # Зелье ученого
    [1, 1, -1, 0, 0, 3, 0, 0, 1],     # Скама
    [0, 0, -2, -1, -1, 0, 0, 0, 1],   # Яд безумия
    [-2, 0, 0, 3, 1, 0, 0, -2, 0],    # Зелье красноречия
])

diseases = np.array([
    [-2, -2, -2, 0, -1, -3, 0, 1, 0],  # Простуда
    [1, 0, -1, -1, -1, 3, 9, 0, 0],    # Каменная хворь
    [-3, -1, 0, 1, -5, 0, 0, 3, 0],    # Чума
])

In [3]:
# Таблица героев:
print(f'{'Имя:':<25} {'Очки навыков:':<15} {'Мощь:':<10}')
for i in range(len(vec_list)):
    points = norm(vec_list[i], ord=1)
    power = round(norm(vec_list[i], ord=2), 2)
    print(f'{names[i]:<25} {points:<15} {power:<10}')

Имя:                      Очки навыков:   Мощь:     
Элерон'Таз                31.0            13.67     
Чилит-в-Глубинах          42.0            16.25     
Ротгарн Стопа             37.0            16.28     
Ульфгард Золотая Струя    37.0            14.25     
Мурка                     37.0            15.39     
Красная машина            110.0           48.48     
Носит-под-Гузник          27.0            9.0       
Куремар                   30.0            14.14     


## Примеры операций:

### Умножение на скаляр:

In [4]:
result = vec_list[0] * mods[1]
print(f"{vec_list[0]} * 1.3 = {result}")

[3 9 3 0 8 2 0 4 2] * 1.3 = [ 3.6 10.8  3.6  0.   9.6  2.4  0.   4.8  2.4]


### Сложение векторов:

In [5]:
result = vec_list[0] + potions[0]
print(f"{vec_list[0]} + {potions[0]} = {result}")

[3 9 3 0 8 2 0 4 2] + [3 0 0 0 0 0 0 0 0] = [6 9 3 0 8 2 0 4 2]


### Норма:

In [6]:
result = round(np.linalg.norm(vec_list[0], ord=2), 2)
print(f"{vec_list[0]} + {potions[0]} = {result}")

[3 9 3 0 8 2 0 4 2] + [3 0 0 0 0 0 0 0 0] = 13.67


### Скалярное произведение векторов:

In [7]:
p_norm1_0 = norm(vec_list[0], ord=2)
p_norm1_1 = norm(vec_list[1], ord=2)
result = vec_list[0] @ vec_list[1] / (p_norm1_0 * p_norm1_1)
result = round(result, 2)

print(f"{vec_list[0]} * {vec_list[1]} = {result}")

[3 9 3 0 8 2 0 4 2] * [2 7 4 9 8 3 0 5 4] = 0.81


### Векторное произведение векторов:

In [8]:
a = vec_list[0][:3]
b = vec_list[1][:3]
result = np.cross(a, b)

print(f"{a} * {b} = {result}")

[3 9 3] * [2 7 4] = [15 -6  3]


## Домашнее задание:

### Задание 1. Магический эксперимент.

Куремар решил провести эксперимент по расширению своих возможностей. Для этого он употребил все зелья из доступных (potions) и, как побочный эффект, получил модификатор сонливости.<p>
Вычислите изменение евклидовой нормы героя, чтобы узнать, стал ли он сильнее.

In [9]:
# Вводные:
kuremar = vec_list[7].copy()
sleepiness = mods[2]
print(kuremar)

[1 3 9 5 1 1 0 9 1]


In [53]:
# Решение:
start_norm = round(np.linalg.norm(kuremar, ord=2), 2)               # норма Куремара до принятия зелий
experiment = (kuremar + sum(potions)) * sleepiness
new_norm = round(np.linalg.norm(experiment, ord=2), 2)              # норма Куремара после принятия зелий 
effect = new_norm - start_norm                                      # полученный эффект

print(f"Евклидова норма Куремара до эксперимента: {start_norm}")
print(f"Евклидова норма Куремара после эксперимента: {new_norm}")
print(f"Изменение евклидовой нормы героя: {effect}")

Евклидова норма Куремара до эксперимента: 14.14
Евклидова норма Куремара после эксперимента: 8.14
Изменение евклидовой нормы героя: -6.0


### Задание 2. Вызов на бой.

Носит-под-Гузник мечтает одолеть Красную машину в бою. Помогите ему в этом.<p>
Наложите нужные модификаторы (mods, potions, diseases) на воинов так, чтобы евклидова норма вектора аутсайдера стала выше чем у противника.<p>
**Можно применить лишь по одному модификатору из каждого списка на одного героя.**<p>

In [15]:
# Вводные:
nappy = vec_list[6].copy()
red_machine = vec_list[5].copy()
print(nappy, red_machine)

[3 3 3 3 3 3 3 3 3] [25 10 10  0 20 30  0  0 15]


In [54]:
worst_potion = min([sum(potion) for potion in potions])                        # зелье с худшим эффектом 
best_potion = max([sum(potion) for potion in potions])                         # зелье с лучшим эффектом

worst_disease = min([sum(disease) for disease in diseases])                    # болезнь с худшим эффектом
best_disease = max([sum(disease) for disease in diseases])                     # болезнь с лучшим эффектом

worst_mod = min(mods)                                                          # состояние с худшим эффектом
best_mod = max(mods)                                                           # состояние с лучшим эффектом

nappy_effect = round(np.linalg.norm((nappy + best_potion + 
                                     best_disease) * best_mod, ord=2), 2)      # лучшие модификаторы - Носит-под-Гузнику
red_effect = round(np.linalg.norm((red_machine + worst_potion + 
                                   worst_disease) * worst_mod, ord=2), 2)      # худшие - Красной машине

print(f"Евклидова норма Носит-под-Гузника: {nappy_effect}")
print(f"Евклидова норма Красной машины: {red_effect}")

if nappy_effect > red_effect: 
    print("Носит-по-Гузник одерживает победу")
else: 
    print("Красную машину не победить")

Евклидова норма Носит-под-Гузника: 114.0
Евклидова норма Красной машины: 15.86
Носит-по-Гузник одерживает победу


### Задание 3. Тест на совместимость.

Мурка решила найти себе подходящую пару. Она испробовала все лунные гороскопы совместимости, но так и не удовлетворилась результатом.<p>
Используйте векторный анализ, чтобы найти для нее наиболее похожего персонажа.<p>

In [25]:
# Вводные:
murka = vec_list[4].copy()
print(murka)

[5 8 1 7 2 9 0 2 3]


In [55]:
# Решение:
def scalar_product(vec1, vec2):
    "Функция для вычисления скалярного произведения"
    p_norm1_0 = norm(vec_list[0], ord=2)
    p_norm1_1 = norm(vec_list[1], ord=2)
    result = vec_list[0] @ vec_list[1] / (p_norm1_0 * p_norm1_1)
    result = round(result, 2)

    return result

similarity = [scalar_product(murka, char) for char in vec_list]         # вычисляем схожесть со всеми персонажами
similarity[4] = -9                                                      # схожесть героя с самим собой: заменяем на отрицательное число

max_sim = max(similarity)
closest = names[similarity.index(max_sim)]                              # ищем персонажа с максимальной схожестью

print(f"Наиболее похожий персонаж для Мурки - {closest}. Схожесть: {max_sim}")

Наиболее похожий персонаж для Мурки - Элерон'Таз. Схожесть: 0.81


### Задание 4. Арена.

Настало время финальной битвы! Герои прибыли на знаменитую арену и разбились на команды. Все, кроме Красной машины, которого оштрафовали за слишком высокий параметр дерзости (его вектор = -1).
Перед тем как начнется битва, участникам предстоит сразиться с великаном, мощь которого равна 60. Те, кто одолеет испытание, пройдут в финальный раунд.

Разъяснение. Используя векторное умножение и евклидову норму, найдите все возможные пары героев и их суммарную мощь. Отсейте тех, кто не набрал 60 очков. Выясните, количество уникальных пар, прошедших в финал, а также, какая команда станет победителем соревнования.

Подведите итоги, сделав информативную статистику:

1. **Основные итоги.** Выведите топ уникальных пар, прошедших в финал в порядке убывания;

2. **Аутсайдеры.** Отдельным списком выведите тех, кто не прошел в финал ни в одной из команд;

3. **Линый результат.** Для каждого героя найдите сумму очков всех команд в которых он принимал участие. Выведите личный вклад героев (включая аутсайдеров) в порядке убывания.

Веди нас, Неревар!

In [4]:
# Вводные:
vec_short_list = vec_list[:, :3].copy()
vec_short_list[5] = [-1, -1, -1]
threshold = norm([60, 0, 0], ord=2)

print(f"Мощь великана: {threshold}\n")
print(f"Таблица героев")
print(f'{'Имя:':<25}{'Сила:':<15}{'Ловкость:':<15}{'Интеллект:':<15}')
for i, row in enumerate(vec_short_list):
    print(f'{names[i]:<25}{row[0]:<15}{row[1]:<15}{row[2]:<15}')

Мощь великана: 60.0

Таблица героев
Имя:                     Сила:          Ловкость:      Интеллект:     
Элерон'Таз               3              9              3              
Чилит-в-Глубинах         2              7              4              
Ротгарн Стопа            9              3              2              
Ульфгард Золотая Струя   7              2              3              
Мурка                    5              8              1              
Красная машина           -1             -1             -1             
Носит-под-Гузник         3              3              3              
Куремар                  1              3              9              


In [36]:
# Решение:
n = len(vec_short_list)                                                               # количество персонажей
pair_list = []                                                                        # список всех возможных пар

for i in range(n-1):
    for j in range(i+1, n):
        char_a = vec_short_list[i]
        char_b = vec_short_list[j]
        pair_power = round(norm(np.cross(char_a, char_b), ord=2), 2)
        pair_list.append([names[i], names[j], pair_power])                            # наполнение списка

print(f"Все возможные пары и их мощь:")
print(f'{'Персонаж 1:':<25}{'Персонаж 2:':<25}{'Суммарная мощь:':<15}')
for row in pair_list:
    print(f'{row[0]:<25}{row[1]:<25}{row[2]:<15}')

finalist_pair_count = len([pair for pair in pair_list if pair[2] > threshold])        # количество пар, прошедших порог мощи
print(f"\nКоличество уникальных пар, прошедших в финал: {finalist_pair_count}")

winners = max(pair_list, key=lambda row: row[2])                                      # наимощнейшая пара
print(f"\nПобедители соревнования: {winners[0]} и {winners[1]}. Их мощь: {winners[2]}")

print(f"\n\nИтоги:\n")

top_finalists = sorted([pair for pair in pair_list if pair[2] > threshold],           # пары, прошедшие в финал
                       key=lambda row: row[2], reverse=True)                          # сортировка по мощи в порядке убывания
print("1. Топ уникальных пары, прошедших в финал:")
print(f'{'Персонаж 1:':<25}{'Персонаж 2:':<25}{'Суммарная мощь:':<15}')
for row in top_finalists:
    print(f'{row[0]:<25}{row[1]:<25}{row[2]:<15}')

outsiders = [
    [name,                                                                            # имя аутсайдера
     max(row[2] for row in pair_list if name in (row[0],row[1]))                      # максимальная мощь пары, в которой был аутсайдер
         ] for name in names.values() 
      if any(name in (row[0], row[1]) for row in top_finalists) == False              # отбор по персонажам, которых нет в списке финалистов
]
print("\n2. Аутсайдеры:")
print(f'{'Персонаж:':<25}{'Максимальная мощь пары:':<15}')
for row in outsiders:
    print(f'{row[0]:<25}{row[1]:<15}')

individual = sorted([
    [name,                                                                            # имя персонажа
     round(sum(row[2] for row in pair_list if name in (row[0],row[1])), 2)            # суммарная мощь пар, в которых был персонаж
         ] for name in names.values()
], key=lambda row: row[1], reverse=True)                                              # сортировка по мощи в порядке убывания
print("\n3. Личный вклад героев:")
print(f'{'Персонаж:':<25}{'Личный вклад:':<15}')
for row in individual:
    print(f'{row[0]:<25}{row[1]:<15}')

Все возможные пары и их мощь:
Персонаж 1:              Персонаж 2:              Суммарная мощь:
Элерон'Таз               Чилит-в-Глубинах         16.43          
Элерон'Таз               Ротгарн Стопа            75.54          
Элерон'Таз               Ульфгард Золотая Струя   61.92          
Элерон'Таз               Мурка                    28.46          
Элерон'Таз               Красная машина           8.49           
Элерон'Таз               Носит-под-Гузник         25.46          
Элерон'Таз               Куремар                  75.89          
Чилит-в-Глубинах         Ротгарн Стопа            65.4           
Чилит-в-Глубинах         Ульфгард Золотая Струя   51.75          
Чилит-в-Глубинах         Мурка                    36.19          
Чилит-в-Глубинах         Красная машина           6.16           
Чилит-в-Глубинах         Носит-под-Гузник         18.49          
Чилит-в-Глубинах         Куремар                  52.9           
Ротгарн Стопа            Ульфгард Золотая Стру