# `NumPy`: матрицы и операции над ними

[Источник](https://github.com/maxis42/Machine-Learning-and-Data-Analysis-Coursera-Yandex-MIPT/blob/master/1%20Mathematics%20and%20Python/Lectures%20notebooks/10%20numpy%20arrays%20and%20operations%20with%20them/matrix_operations-.ipynb)

In [1]:
import numpy as np

## 1. Создание матриц

In [4]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print("Матрица:\n", a)

Матрица:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


In [5]:
b = np.eye(5)
print("Единичная матрица:\n", b)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
c = np.ones((7, 5))
print("Матрица, состоящая из одних единиц:\n", c)

Матрица, состоящая из одних единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
v = np.arange(0, 24, 2)
print("Вектор-столбец:\n", v)

Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [9]:
d = v.reshape((3, 4))
print("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


## 2. Индексирование

In [10]:
print("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [11]:
print("Второй элемент третьей строки матрицы:", d[2, 1])

Второй элемент третьей строки матрицы: 18


In [12]:
print("Вторая строка матрицы d:\n", d[1, :])
print("Четвертый столбец матрицы d:\n", d[:, 3])

Вторая строка матрицы d:
 [ 8 10 12 14]
Четвертый столбец матрицы d:
 [ 6 14 22]


In [13]:
print("Элементы матрицы d с координатами (1, 2) и (0, 3):\n", d[[1, 0], [2, 3]])

Элементы матрицы d с координатами (1, 2) и (0, 3):
 [12  6]


## 3. Векторы, вектор-строки и вектор-столбцы

In [14]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [15]:
print("Вектор:\n", a)
print("Его размерность:\n", a.shape)
print("Двумерный массив:\n", b)
print("Его размерность:\n", b.shape)

Вектор:
 [1 2 3]
Его размерность:
 (3,)
Двумерный массив:
 [[1]
 [2]
 [3]]
Его размерность:
 (3, 1)


In [16]:
a = a.T
b = b.T

In [17]:
print("Вектор не изменился:\n", a)
print("Его размерность также не изменилась:\n", a.shape)
print("Транспонированный двумерный массив:\n", b)
print("Его размерность изменилась:\n", b.shape)

Вектор не изменился:
 [1 2 3]
Его размерность также не изменилась:
 (3,)
Транспонированный двумерный массив:
 [[1 2 3]]
Его размерность изменилась:
 (1, 3)


## 4. Умножение матриц и столбцов

In [18]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [19]:
print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат умножения функцией:\n", r1)
print("Результат умножения методом:\n", r2)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]


In [20]:
c = np.array([1, 2])
r3 = b.dot(c)

In [21]:
print("Матрица:\n", b)
print("Вектор:\n", c)
print("Результат умножения:\n", r3)

Матрица:
 [[4 1]
 [2 2]]
Вектор:
 [1 2]
Результат умножения:
 [6 6]


In [22]:
r = a * b

In [23]:
print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат покоординатного умножения через операцию *:\n", r)

Матрица A:
 [[1 0]
 [0 1]]
Матрица B:
 [[4 1]
 [2 2]]
Результат покоординатного умножения через операцию *:
 [[4 0]
 [0 2]]


## 5. Транспонирование матриц

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [25]:
print("Матрица:\n", a)
print("Транспонирование функцией:\n", b)
print("Транспонирование методом:\n",  c)

Матрица:
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


## 6. Определитель матрицы

In [26]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [27]:
print("Матрица:\n", a)
print("Определитель:\n", det)

Матрица:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Определитель:
 -1.0


## 7. Ранг матрицы

In [28]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [29]:
print("Матрица:\n", a)
print("Ранг матрицы:", r)

Матрица:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Ранг матрицы: 2


С помощью вычисления ранга матрицы можно проверять линейную независимость системы векторов.

In [30]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [31]:
print(np.linalg.matrix_rank(m) == m.shape[0])

True


## 8. Системы линейных уравнений

In [32]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

In [33]:
print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Решение системы:\n", x)

Матрица A:
 [[3 1]
 [1 2]]
Вектор b:
 [9 8]
Решение системы:
 [2. 3.]


Убедимся, что вектор x действительно является решением системы:

In [34]:
print(a.dot(x))

[9. 8.]


Бывают случаи, когда решение системы не существует. Но хотелось бы все равно "решить" такую систему. Логичным кажется искать такой вектор 
$x$, который минимизирует выражение $||Ax-b||^2$ — так мы приблизим выражение $Ax$ к $b$.

In [35]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b)

In [36]:
print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Псевдорешение системы:\n", x)

Матрица A:
 [[0 1]
 [1 1]
 [2 1]
 [3 1]]
Вектор b:
 [-1.   0.2  0.9  2.1]
Псевдорешение системы:
 [ 1.   -0.95]


## 9. Обращение матриц

In [37]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)

In [38]:
print("Матрица A:\n", a)
print("Обратная матрица к A:\n", b)
print("Произведение A на обратную должна быть единичной:\n", a.dot(b))

Матрица A:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Обратная матрица к A:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
Произведение A на обратную должна быть единичной:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 10. Собственные числа и собственные вектора матрицы

In [39]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [40]:
print("Матрица A:\n", a)
print("Собственные числа:\n", w)
print("Собственные векторы:\n", v)

Матрица A:
 [[-1 -6]
 [ 2  6]]
Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


## 11. Комплексные числа в питоне

In [41]:
a = 3 + 2j
b = 1j

In [42]:
print("Комплексное число a:\n", a)
print("Комплексное число b:\n", b)

Комплексное число a:
 (3+2j)
Комплексное число b:
 1j


С комплексными числами в питоне можно производить базовые арифметические операции так же, как и с вещественными числами:

In [43]:
c = a * a
d = a / (4 - 5j)

In [44]:
print("Комплексное число c:\n", c)
print("Комплексное число d:\n", d)

Комплексное число c:
 (5+12j)
Комплексное число d:
 (0.0487804878048781+0.5609756097560976j)
